-- AlterTable
ALTER TABLE `server` ADD COLUMN `cpuUsage` DOUBLE NULL DEFAULT 0,
    ADD COLUMN `diskUsage` DOUBLE NULL DEFAULT 0,
    ADD COLUMN `ipAddress` VARCHAR(191) NULL,
    ADD COLUMN `lastPing` DATETIME(3) NULL,
    ADD COLUMN `macAddress` VARCHAR(191) NULL,
    ADD COLUMN `memoryUsage` DOUBLE NULL DEFAULT 0,
    ADD COLUMN `networkIn` DOUBLE NULL DEFAULT 0,
    ADD COLUMN `networkOut` DOUBLE NULL DEFAULT 0,
    ADD COLUMN `rootPassword` VARCHAR(191) NULL,
    ADD COLUMN `sshPublicKey` VARCHAR(191) NULL,
    MODIFY `status` VARCHAR(191) NOT NULL DEFAULT 'creating';
